'use client'

import type { AnalysisResult } from '../api-client/analysisApi'
import { Button } from './Button'
import { MaterialIcon } from './MaterialIcon'
import { generatePdfReport } from '../utils/pdfReport'

type ReportsFooterProps = {
  result?: AnalysisResult | null
  completedAt?: string | null
}

export function ReportsFooter({ result, completedAt }: ReportsFooterProps) {
  return (
    <footer className="reports-footer">
      <div>
        <div className="verified-icon">
          <MaterialIcon name="verified_user" />
        </div>
        <div>
          <p>Evidence packet generated by FoldEx</p>
          <span>Research support only. Not a diagnostic report.</span>
        </div>
      </div>
      <div className="reports-footer-actions">
        <Button
          className="reports-download"
          disabled={!result}
          onClick={() => result && generatePdfReport(result, completedAt)}
        >
          Download PDF Report
        </Button>
      </div>
    </footer>
  )
}
